

// 艺术字地图数据 - 使用连续的字符绘制地图轮廓
export const MAP_1 = [
    // 样式1
    '.................................',
    '................................///...............',
    '.....................       ..//EEEE//.........................//EEEEEEEE//..................................                  ......///.......//EEEEE//........                          ...............................',
    '...........................//EEEEEEEEE//.....................//EEEEEEEEEEEEEEEEE//.............                  .................//EEE//..//EEEEEEEEEEEEEEEEE//...........................................................',
    '...............        .//EEEEEEEEEEEEEEEEE//.......  ....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//............................//EEEEEEEE//EEEEEEEEEEEEEEEEEEEEEE//.................                      .................',
    '......  ...   ......//EEEEEEEEEEEEEEEEEEEEEEEEE//......//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...............   .........//..........................',
    '..     .... ............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.........          ....//EE//........................',
    '......  ... ....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...........      ..//EEE//.......................',
    '.....   ..     .....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.................//EEEE//...        ............',
    '.................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...............//EE//....          ..........',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...........///......       ..............',
    '.........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//........................         .....',
    '........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.................    ............',
    '...................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//................................',
    '................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//..........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//................................',
    '....................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.....    ...//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//........       .   ....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//..................................',
    '..................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...................///EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//....              ....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//............   .......................',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...............      ...//EEEEEEEEEEEEEEEEEEEEEEEEEEE//............              .....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//............  .........   .............',
    '.............//EEEEEEEEEEEEEEEEEEEEEEEEEEE//........      .....      .....//EEEEEEEEEEEEEEEEEEEEEEEEEEEE//........                  .....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.   ...          ...........................',
    '.................//EEEEEEEEEEEEEEEEEEEEEEEEE//...........                 ...//EEEEEEEEEEE//.....//................                    .....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//..              ................................',
    '..................//EEEEEEEEEEEEEEEEEEEEEEEEEE//......                  ........//EEEEEEEEEE//...//EEE//..........                          ....//EEEEEEEEEEEEEEEEEEEEEEEE//...   ./        ....................................',
    '.....................//EEEEEEEEEEEEEEEEEEEEEEEEEE//........               ......//EEEEEEEEEEEEE//...........///........                 ..........//EEEEEEEEEEEEEEEEEE//...    ..//.       .....................................',
    '..........           ./  .//EEEEEEEEEEEEEEEEEEEEEE//.............           ......//EEEEEEEEEE//......... //EEE//.........          ..........//EEEEEEEEEEEEEEEEEE//....    ...//.           .......    .........................',
    '.............       ./   ...//EEEEEEEEEEEEEEEE//............///......           ...//EEEEEEE//....//EEE//.............          ..........//EEEEEEEEEEEEEEEEE//....     ...//...             ......      .........................',
    '.........         ../      ....//EEEEEEEEEE//...........///.E.///......          ...//EEEE//.......//EEEEE//..../........          .... .//EEEEEEEEEEEEEEE//....    ...//...               ....       .............................',
    '.......         .../        ...//EEEEEE//..............///EEE///........           .................//EEEE//..../........          ........//EEEEEEEEE//.....    ...//E//..           ......         ..............................',
    '......           ../      ......//EE//........    .......//.EE.///........           ................//EEE//............          ...........//EE//......     ...//EEEE//..                       ..................................',
    '......           ../       ......//.............   ........///EEE//......               ..........................                   .........//....       ..//EEEEE//...                  ...........................................',
    '......             ./        .....//...........    .........///......                              ...........                         ...........      ....//EEE//...                      ........................................',
    '..............//               ..............          ..........                                   ..........                        .....................//EE//...................................................................',
    '.....//....                     ......                                                               ........................................................//.....................',

];


export const MAP_2 = [
    // 样式1
    '.................................',
    '....................//...............',
    '........................//EEEEEEE//..............',
    '.................//////EEEEEEEEEEEEEEEE//...............................................',
    '................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.............',
    '......  ...   ......//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//............',
    '..     .... ..............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...........',
    '......  ... ....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//..........',
    '.....   ..          ........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.........',
    '...............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//........',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.......',
    '.........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//......',
    '........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.....',
    '...................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//....',
    '................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...',
    '....................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//..........',
    '..................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//....',
    '.............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.',
    '...........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//....',
    '.............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//......    ........//////EEEEEEEEEE//...//////.............',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEEEE//........           ............//////EEEEEEEEEE//...//////.............',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEE//.............           ............//////EEEEEEEEEE//...//////.............',
    '..............//EEEEEEEEEEEEEEEE//........///..........           ............//////EEEEEEEEEE//....//////.............',
    '..............//EEEEEEEEEE//...........///.E.///.........           ................/////EEEEE//....////........',
    '..............//EEEEEE//..............///EEE///............           ................/////EEEEE//....////........',
    '..............//EE//....................//.EE.///........           ................///EEE//.....//........',
    '..............//.......................///EEE//...///.///.....           ................/////EEEEE//////........',
    '..............//..........................///......           ................/////EEEEE//////........',
    '..............//...............................',
    '.....//..............................',
]


export const MAP_3 = [
    // 样式1
    '.................................',
    '....................//...............',
    '...................////..............',
    '.................//////EEEEEEEEEEEEEEEE/////////////////////...............................................',
    '................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.............',
    '......  ...   ......//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//............',
    '..     .... ..............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...........',
    '......  ... ....//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//..........',
    '.....   ..          ........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.........',
    '...............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//........',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.......',
    '.........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//......',
    '........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.....',
    '...................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//....',
    '................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...',
    '....................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//..........',
    '..................//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//...........',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//....',
    '.............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//.',
    '...........//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//....',
    '.............//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE//......    ........//EEEEEEEEEE//...//EEE//.............',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEEEE//........           ............//EEEEEEEEEE//...//////.............',
    '..............//EEEEEEEEEEEEEEEEEEEEEEEE//.............           ............//EEEEEEEEEE//...//////.............',
    '..............//EEEEEEEEEEEEEEEE//........///..........           ............//////EEEEEEEEEE//....//////.............',
    '..............//EEEEEEEEEE//...........///.E.///.........           ................/////EEEEE//....////........',
    '..............//EEEEEE//..............///EEE///............           ................/////EEEEE//....////........',
    '..............//EE//....................//.EE.///........           ................///EEE//.....//........',
    '..............//.......................///EEE//...///.///.....           ................/////EEEEE//////........',
    '..............//..........................///......           ................/////EEEEE//////........',
    '..............//...............................',
    '.....//..............................',
]