export const WIKI_TRUTH_EVENT_SIGNATURES = [
  'event BoxListed(uint256 indexed boxId, uint256 indexed userId, address acceptedToken)',
  'event BoxPurchased(uint256 indexed boxId, uint256 indexed userId)',
  'event BidPlaced(uint256 indexed boxId, uint256 indexed userId)',
  'event CompleterAssigned(uint256 indexed boxId, uint256 indexed userId)',
  'event RequestDeadlineChanged(uint256 indexed boxId, uint256 deadline)',
  'event ReviewDeadlineChanged(uint256 indexed boxId, uint256 deadline)',
  'event RefundPermitChanged(uint256 indexed boxId, bool permission)',
  'event OrderAmountDeposited(uint256 indexed boxId, uint256 indexed userId, address indexed token, uint256 amount)',
  'event OrderAmountWithdraw(uint256[] list, address indexed token, uint256 indexed userId, uint256 amount)',
  'event RewardAmountAdded(uint256 indexed boxId, address indexed token, uint256 amount, uint8 rewardType)',
  'event HelperRewrdsWithdraw(uint256 indexed userId, address indexed token, uint256 amount)',
  'event RewardsWithdraw(uint256 indexed userId, address indexed token, uint256 amount)',
  'event BoxInfoChanged(uint256 indexed boxId, string boxInfoCID)',
  'event BoxCreated(uint256 indexed boxId, uint256 indexed userId)',
  'event BoxStatusChanged(uint256 indexed boxId, uint8 status)',
  'event PriceChanged(uint256 indexed boxId, uint256 price)',
  'event DeadlineChanged(uint256 indexed boxId, uint256 deadline)',
  'event PrivateKeyPublished(uint256 indexed boxId, bytes privateKey, uint256 indexed userId)',
  'event Blacklist(address user, bool status)',
  // 'event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)',
  // 'event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)',
  // 'event ApprovalForAll(address indexed owner, address indexed operator, bool approved)',
] as const
